"""add_request_id

Revision ID: 13e9b8a0aff1
Revises: c7d8e9f0a1b2
Create Date: 2026-07-16 14:18:12.326052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e9b8a0aff1'
down_revision: Union[str, None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.alter_column('chat_messages', 'match_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_request_id'), 'chat_messages', ['request_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'match_requests', ['request_id'], ['id'])
    op.add_column('matches', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_matches_request_id'), 'matches', ['request_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'match_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_request_id'), table_name='matches')
    op.drop_column('matches', 'request_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_request_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'match_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chat_messages', 'request_id')
    # ### end Alembic commands ###
