"""Initial migration

Revision ID: 438f614cd145
Revises: 
Create Date: 2026-05-15 15:42:13.536138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438f614cd145'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('completed_rides_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('is_onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('device_token', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_phone'), 'profiles', ['phone'], unique=True)
    op.create_table('ride_pings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_area', sa.String(length=200), nullable=True),
    sa.Column('destination_text', sa.String(length=300), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('estimated_fare', sa.Float(), nullable=False),
    sa.Column('final_fare', sa.Float(), nullable=True),
    sa.Column('gender_preference', sa.String(length=10), nullable=True),
    sa.Column('meetup_point', sa.String(length=200), nullable=True),
    sa.Column('passenger_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_pings_host_id'), 'ride_pings', ['host_id'], unique=False)
    op.create_table('match_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ride_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_pings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_requests_guest_id'), 'match_requests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_match_requests_host_id'), 'match_requests', ['host_id'], unique=False)
    op.create_index(op.f('ix_match_requests_ride_id'), 'match_requests', ['ride_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ride_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_pings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_guest_id'), 'matches', ['guest_id'], unique=False)
    op.create_index(op.f('ix_matches_host_id'), 'matches', ['host_id'], unique=False)
    op.create_index(op.f('ix_matches_ride_id'), 'matches', ['ride_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_match_id'), 'chat_messages', ['match_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_match_id'), 'ratings', ['match_id'], unique=False)
    op.create_index(op.f('ix_ratings_reviewed_user_id'), 'ratings', ['reviewed_user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reported_user_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ratings_reviewed_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_match_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_chat_messages_match_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_matches_ride_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_host_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_guest_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_match_requests_ride_id'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_host_id'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_guest_id'), table_name='match_requests')
    op.drop_table('match_requests')
    op.drop_index(op.f('ix_ride_pings_host_id'), table_name='ride_pings')
    op.drop_table('ride_pings')
    op.drop_index(op.f('ix_profiles_phone'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
