"""Add blocked_users table

Revision ID: b1c2d3e4f5g6
Revises: 5f7c9d3e1a2b
Create Date: 2026-05-18 09:47:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5g6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_users_blocked_id'), 'blocked_users', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocked_users_blocker_id'), 'blocked_users', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_users_blocker_id'), table_name='blocked_users')
    op.drop_index(op.f('ix_blocked_users_blocked_id'), table_name='blocked_users')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###