"""Add PostGIS for RidePing

Revision ID: eb3a6e3b165f
Revises: 438f614cd145
Create Date: 2026-05-15 16:38:15.704608

"""
from typing import Sequence, Union
import logging


from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'eb3a6e3b165f'
down_revision: Union[str, None] = '438f614cd145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
logger = logging.getLogger("uvicorn")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.add_column('profiles', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('ride_pings', sa.Column('pickup_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.add_column('ride_pings', sa.Column('destination_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_column('ride_pings', 'pickup_lat')
    op.drop_column('ride_pings', 'destination_lng')
    op.drop_column('ride_pings', 'pickup_lng')
    op.drop_column('ride_pings', 'destination_lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_pings', sa.Column('destination_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ride_pings', sa.Column('pickup_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ride_pings', sa.Column('destination_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ride_pings', sa.Column('pickup_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index('idx_ride_pings_pickup_geom', table_name='ride_pings', postgresql_using='gist')
    op.drop_index('idx_ride_pings_destination_geom', table_name='ride_pings', postgresql_using='gist')
    op.drop_column('ride_pings', 'destination_geom')
    op.drop_column('ride_pings', 'pickup_geom')
    op.drop_column('profiles', 'is_admin')
    # ### end Alembic commands ###
